# GitHub Actions CI script for mkpsxiso
# (C) 2021 spicyjpeg

name: Build mkpsxiso
on:   push 

jobs:
  build-alpine:
    name:    Build mkpsxiso on alpine
    runs-on: ubuntu-latest
    container: 
      image: alpine:latest

    steps:
    - name: apk prep
      run: |
        apk update
        apk add cmake make git openssh g++

    - name: Fetch repo contents
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build and package mkpsxiso
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: mkpsxiso-alpine
        path: build/mkpsxiso

  # This job takes care of creating a new release and upload the build
  # artifacts if the last commit is associated to a tag.
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-alpine
    steps:
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          name: mkpsxiso for Alpine Linux
          prerelease: true
          tag_name: latest
          files: |
            build/mkpsxiso
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

